config/routes.rb
Rails.application.routes.draw do
    # This posts the information entered by user to the ContactsController, allowing it to do work on the user submitted info via POST.
    # Formally, this generates a route helper that creates a URL and hands off the request to the controller (ContactsController).
    resources :contacts, only: [:new, :create]
    root to: 'visitors#new'
end

app/models/contact.rb
class Contact
    include ActiveModel::Model
    attr_accessor :name, :string
    attr_accessor :email, :string
    attr_accessor :content, :string
    attr_accessor :icecream, :string
    
    validates_presence_of :name
    validates_presence_of :email
    validates_presence_of :content
    validates_format_of   :email,
        with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
    validates_length_of :content, :maximum => 500
    
end

app/models/owner.rb
class Owner
    
    def name
        name = 'Donne Ellstrom'
    end
    
    # My birthday.
    def birthdate
        birthdate = Date.new(1985, 11, 15)
    end
    
    #Compares birthdate to today to see how many days until next birthday, returns an integer.
    def birthday_countdown
        today = Date.today
        birthday = Date.new(today.year, birthdate.month, birthdate.day)
        if birthday > today
            birthday_countdown = (birthday - today).to_i
        else
            birthday_countdown = (birthday.next_year - today).to_i
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end

    def create
        @contact = Contact.new(secure_params)
            if @contact.valid?
                # TODO send message
                flash[:notice] = "Message sent from #{@contact.name}."
                redirect_to root_path
            else
                render :new
            end
    end

    private
        def secure_params
            params.require(:contact).permit(:name, :email, :content, :icecream)
        end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  
  def new
    @owner = Owner.new
    
    #This is implied by 'new' method
    #render 'visitors/new'
    #flash.now[:notice] = 'Welcome! This is a flash success test.'
    # Must use "" marks if embedding ruby insisde flash message, otherwise ''.
    #flash.now[:alert] = "My birthday is soon, only #{@owner.birthday_countdown} days until my next lonely birthday. This is a flash alert test."
    #flash.now[:warning] = "Cory Dumping James?!?!?!?!"
  
    # Using flash.now will make sure the message only appears on the rendered
    # page and will not persist after a user follows a link to a new page.
    # If you ever see a “sticky” flash message that won’t go away, you need to use
    # flash.now instead of flash
  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/contacts/new.html.erb
<% content_for :title do %>Contact<% end %>
<h3>Contact</h3>
<div class="form">
    <%= simple_form_for @contact do |form| %>
        <%= form.error_notification %>
        <%= form.input :name, autofocus: true %>
        <%= form.input :email %>
        <%= form.input :content, as: :text %>
        <%= form.select :icecream, ['*Your Favorite Ice Cream', 'Mint', 'Vanilla Mint', 'Minty Mint', 'Double Mint'] %>
        <%= form.button :submit, 'Submit', class: 'submit' %>
    <% end %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <!-- checks to make sure we are only evaluating string !-->
  <% if msg.is_a?(String) %>
    <!-- CSS styling for button, ERB to evaluate flash type using ternary. If notice = true, success flash, else, alert flash !-->
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <!-- ERB to create a div for the message to exist in !-->
      <%= content_tag :div, msg %>
      <!-- small 'x' button to close flash message !-->
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Contact', new_contact_path  %></li>
<li><%= link_to 'Blog', page_path('blog') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Workspace" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Workspace" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  
    <footer class="row">
      <section class="small-12 medium-4 columns"> Copyright 2016 by Donne Ellstrom </section> 
      <section class="small-12 medium-8 columns"> All rights revoked. </section>
    </footer>
  
  </body>

</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>

<h3>About Foobar Kadigan</h3>

<p>He was born in Waikikamukau, New Zealand. He left New Zealand for England,
excelled at the University of Mopery, and served in the Royal Loamshire Regiment.
While in service, he invented the kanuten valve used in the processing of
unobtainium for industrial use. With a partner, Granda Fairbook, he founded
Acme Manufacturing, later acquired by the Advent Corporation, to develop his
discovery for use in the Turboencabulator. Mr. Kadigan is now retired and
lives in Middlehampton with a favorite cat, where he raises Griadium frieda
and collects metasyntactic variables.</p>

<p>His favorite quotation is:</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua.</p>

app/views/pages/blog.html.erb
<h1>My Blog...</h1>

app/views/visitors/Controller.html.erb
<h1>Visitors#Controller</h1>
<p>Find me in app/views/visitors/Controller.html.erb</p>

app/views/visitors/new.html.erb
<h3>Home</h3>
<p>Welcome to the home of <%= @owner.name %>.</p>
<p>I was born on <%= @owner.birthdate %>.</p>
<p>Only <%= @owner.birthday_countdown %> days until my next lonely birthday... </p>

<% content_for :sidebar do %>
<h3>Contact Info</h3>
<p>Email: me@example.com</p>
<% end %>
<h3>Main</h3>
<p>Welcome!</p>

<% content_for :sidebar do %>
<h3>Contact Info</h3>
<p>Email: me@example.com</p>
<% end %>